import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Button } from '../components/ui/button';
import { Code, Smartphone, Brain, Trophy, Sparkles, BookOpen, Target, Users, ArrowRight, CheckCircle2 } from 'lucide-react';

const HomePage = () => {
  const navigate = useNavigate();

  const features = [
    {
      icon: Sparkles,
      title: 'AI-Powered Roadmaps',
      description: 'Get personalized learning paths generated by Claude Sonnet 4 based on your goals, time, and skill level',
      color: 'from-cyan-500 to-blue-600'
    },
    {
      icon: BookOpen,
      title: 'Complete Language Guides',
      description: 'Master Python, Java, C++, and JavaScript with comprehensive internal tutorials - no external links needed',
      color: 'from-blue-500 to-purple-600'
    },
    {
      icon: Trophy,
      title: 'Dynamic Problem Sets',
      description: 'AI-generated coding problems with hints and solutions. Earn points as you solve: Easy +2, Medium +5, Hard +10',
      color: 'from-purple-500 to-pink-600'
    },
    {
      icon: Target,
      title: '4 Learning Tracks',
      description: 'Choose from Web Development, App Development, AI/ML, or DSA & Competitive Programming',
      color: 'from-pink-500 to-red-600'
    }
  ];

  const tracks = [
    {
      icon: Code,
      name: 'Web Development',
      description: 'Build modern websites and web applications'
    },
    {
      icon: Smartphone,
      name: 'App Development',
      description: 'Create mobile apps for iOS and Android'
    },
    {
      icon: Brain,
      name: 'AI / Machine Learning',
      description: 'Master AI and ML algorithms'
    },
    {
      icon: Trophy,
      name: 'DSA & Competitive Programming',
      description: 'Excel in problem-solving'
    }
  ];

  const benefits = [
    'Personalized learning paths tailored to YOUR goals',
    'AI-powered content generation for roadmaps and problems',
    'Gamified point system to track your progress',
    'Internal learning resources - everything in one place',
    'No scattered tutorials or random YouTube playlists',
    'Community-focused for NST students'
  ];

  return (
    <div className="min-h-screen" style={{ background: 'linear-gradient(135deg, rgb(3,7,18) 0%, rgb(6,15,35) 100%)' }}>
      {/* Hero Section */}
      <div className="relative overflow-hidden">
        {/* Decorative background elements */}
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
          <div className="absolute -top-40 -right-40 w-80 h-80 bg-cyan-500/10 rounded-full blur-3xl"></div>
          <div className="absolute top-60 -left-40 w-96 h-96 bg-blue-500/10 rounded-full blur-3xl"></div>
        </div>

        <div className="relative max-w-7xl mx-auto px-6 py-12">
          {/* Navigation */}
          <nav className="flex items-center justify-between mb-20">
            <h1 className="text-3xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-blue-500" data-testid="home-logo">
              NSTrack
            </h1>
            <div className="flex items-center gap-4">
              <Button
                variant="ghost"
                onClick={() => navigate('/login')}
                className="text-slate-300 hover:text-cyan-400"
                data-testid="home-login-btn"
              >
                Login
              </Button>
              <Button
                onClick={() => navigate('/signup')}
                className="bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-600 hover:to-blue-700 text-white font-semibold"
                data-testid="home-signup-btn"
              >
                Get Started
              </Button>
            </div>
          </nav>

          {/* Hero Content */}
          <div className="text-center mb-20 animate-fade-in">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-cyan-500/10 border border-cyan-500/20 mb-6">
              <Users className="w-4 h-4 text-cyan-400" />
              <span className="text-cyan-400 text-sm font-medium">Built for NST Students</span>
            </div>
            
            <h2 className="text-5xl sm:text-6xl lg:text-7xl font-bold text-white mb-6 leading-tight">
              Your AI-Powered
              <br />
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-blue-500">
                Learning Mentor
              </span>
            </h2>
            
            <p className="text-xl text-slate-300 mb-8 max-w-3xl mx-auto">
              Stop struggling with scattered resources. NSTrack creates personalized learning paths, 
              generates practice problems, and guides you from basics to mastery - all in one place.
            </p>
            
            <div className="flex items-center justify-center gap-4">
              <Button
                onClick={() => navigate('/signup')}
                size="lg"
                className="bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-600 hover:to-blue-700 text-white font-semibold px-8 py-6 text-lg"
                data-testid="hero-get-started-btn"
              >
                Start Learning Now
                <ArrowRight className="w-5 h-5 ml-2" />
              </Button>
              <Button
                onClick={() => document.getElementById('features')?.scrollIntoView({ behavior: 'smooth' })}
                size="lg"
                variant="outline"
                className="border-cyan-500 text-cyan-400 hover:bg-cyan-500/10 px-8 py-6 text-lg"
                data-testid="learn-more-btn"
              >
                Learn More
              </Button>
            </div>
          </div>
        </div>
      </div>

      {/* Features Section */}
      <div id="features" className="max-w-7xl mx-auto px-6 py-20">
        <div className="text-center mb-16">
          <h3 className="text-4xl font-bold text-white mb-4">Everything You Need to Succeed</h3>
          <p className="text-lg text-slate-300">AI-powered features designed to accelerate your learning</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-20">
          {features.map((feature, index) => {
            const Icon = feature.icon;
            return (
              <div
                key={index}
                className="glass-effect rounded-2xl p-8 hover-glow"
                data-testid={`feature-${index}`}
              >
                <div className={`w-14 h-14 rounded-xl bg-gradient-to-r ${feature.color} flex items-center justify-center mb-6`}>
                  <Icon className="w-7 h-7 text-white" />
                </div>
                <h4 className="text-2xl font-bold text-white mb-3">{feature.title}</h4>
                <p className="text-slate-300 text-lg">{feature.description}</p>
              </div>
            );
          })}
        </div>

        {/* Learning Tracks */}
        <div className="mb-20">
          <div className="text-center mb-12">
            <h3 className="text-4xl font-bold text-white mb-4">Choose Your Path</h3>
            <p className="text-lg text-slate-300">Select from 4 specialized learning tracks</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
            {tracks.map((track, index) => {
              const Icon = track.icon;
              return (
                <div
                  key={index}
                  className="glass-effect rounded-xl p-6 text-center hover-glow"
                  data-testid={`track-preview-${index}`}
                >
                  <div className="w-12 h-12 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 flex items-center justify-center mx-auto mb-4">
                    <Icon className="w-6 h-6 text-white" />
                  </div>
                  <h5 className="text-lg font-bold text-white mb-2">{track.name}</h5>
                  <p className="text-slate-400 text-sm">{track.description}</p>
                </div>
              );
            })}
          </div>
        </div>

        {/* Benefits */}
        <div className="glass-effect rounded-2xl p-12">
          <div className="text-center mb-10">
            <h3 className="text-4xl font-bold text-white mb-4">Why Choose NSTrack?</h3>
            <p className="text-lg text-slate-300">Built specifically for college students who want clear, structured learning</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-4xl mx-auto">
            {benefits.map((benefit, index) => (
              <div key={index} className="flex items-start gap-3" data-testid={`benefit-${index}`}>
                <CheckCircle2 className="w-6 h-6 text-cyan-400 flex-shrink-0 mt-1" />
                <p className="text-slate-300 text-lg">{benefit}</p>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* CTA Section */}
      <div className="max-w-7xl mx-auto px-6 py-20">
        <div className="glass-effect rounded-2xl p-12 text-center">
          <h3 className="text-4xl font-bold text-white mb-6">
            Ready to Transform Your Learning Journey?
          </h3>
          <p className="text-xl text-slate-300 mb-8 max-w-2xl mx-auto">
            Join NSTrack today and get your personalized AI-powered learning roadmap in minutes
          </p>
          <Button
            onClick={() => navigate('/signup')}
            size="lg"
            className="bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-600 hover:to-blue-700 text-white font-semibold px-12 py-6 text-xl"
            data-testid="cta-signup-btn"
          >
            Get Started Free
            <ArrowRight className="w-6 h-6 ml-2" />
          </Button>
        </div>
      </div>

      {/* Footer */}
      <footer className="border-t border-slate-800 py-8">
        <div className="max-w-7xl mx-auto px-6 text-center text-slate-400">
          <p>© 2025 NSTrack - AI-Powered Learning Mentor for NST Students</p>
        </div>
      </footer>
    </div>
  );
};

export default HomePage;